[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = ""
name = "chagic"
tablePrefix = "chagic_"

[redis]

[server]
mode = "debug"
port = ":8080"

[log]
level = "debug"
path = "logs/chat.log"
