definitions:
  model.Chat:
    properties:
      active_users:
        type: string
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      participant_count:
        type: integer
      type:
        $ref: '#/definitions/model.ChatType'
      updated_at:
        type: string
    type: object
  model.ChatType:
    enum:
    - private
    - group
    type: string
    x-enum-varnames:
    - ChatTypePrivate
    - ChatTypeGroup
info:
  contact: {}
paths:
  /chat/list:
    get:
      consumes:
      - application/json
      description: get chats
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0,"data": model.Chat , "msg": "string","success":
            true}'
          schema:
            $ref: '#/definitions/model.Chat'
      summary: List Chats
      tags:
      - chat
swagger: "2.0"
